language: node_js
node_js:
  - "6.3.1"

deploy:
  provider: npm
  email: thomas.winckell@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true

after_success:
  - codeclimate-test-reporter < ./coverage/lcov.info

addons:
  code_climate:
    repo_token: $CODE_CLIMATE_TOKEN