language: node_js
node_js:
  - "6.3.1"

script:
  - npm run build
  - npm run test

deploy:
  - provider: npm
    email: thomas.winckell@gmail.com
    api_key: $NPM_TOKEN
    skip_cleanup: true
    on:
      tags: true
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: "travis-demo-client.winckell.com"
    region: "eu-central-1"
    skip_cleanup: true
    local_dir: ./build
    on:
      tags: true
  - provider: pages
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    email: thomas.winckell@gmail.com
    skip_cleanup: true
    local_dir: ./build
    on:
      tags: true

after_success:
  - codeclimate-test-reporter < ./coverage/lcov.info

addons:
  code_climate:
    repo_token: $CODE_CLIMATE_TOKEN

notifications:
  email:
    recipients:
      - thomas.winckell@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
  slack:
    rooms:
      - secure: $SLACK_TOKEN
      on_success: always # default: always
      on_failure: always # default: always