language: node_js
node_js:
  - "6.3.1"

deploy:
  - provider: npm
    email: thomas.winckell@gmail.com
    api_key: $NPM_TOKEN
    on:
      tags: true
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: "travis-demo-client"
    skip_cleanup: true
    on:
      tags: true

after_success:
  - codeclimate-test-reporter < ./coverage/lcov.info

addons:
  code_climate:
    repo_token: $CODE_CLIMATE_TOKEN

notifications:
  email:
    recipients:
      - thomas.winckell@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
  slack: $SLACK_TOKEN